version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: medic_db
      POSTGRES_USER: medic_user
      POSTGRES_PASSWORD: medic_password_secure_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - USE_POSTGRES=true
      - DB_NAME=medic_db
      - DB_USER=medic_user
      - DB_PASSWORD=medic_password_secure_2024
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-change-this-in-production-2024-very-long-secret-key
      - DEBUG=True
      - ALLOWED_HOSTS=*
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:
