# Generated by Django 5.0.7 on 2024-08-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('last_name', models.TextField()),
                ('dni', models.TextField()),
                ('birth_date', models.DateField()),
                ('gender', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('consult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='history.consult')),
            ],
        ),
        migrations.AddField(
            model_name='consult',
            name='idDr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.dr'),
        ),
        migrations.AddField(
            model_name='dr',
            name='idPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.person'),
        ),
        migrations.AddField(
            model_name='consult',
            name='idPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.person'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('consult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='history.consult')),
            ],
        ),
    ]
