# Generated by Django 5.0.7 on 2025-09-21 23:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('consult_type', models.CharField(choices=[('FIRST', 'Primera Consulta'), ('FOLLOW', 'Consulta de Seguimiento'), ('EMERGENCY', 'Emergencia'), ('ROUTINE', 'Consulta de Rutina')], default='FIRST', max_length=10, verbose_name='Tipo de Consulta')),
                ('reason', models.TextField(verbose_name='Motivo de Consulta')),
                ('symptoms', models.TextField(verbose_name='Síntomas')),
                ('vital_signs', models.TextField(blank=True, null=True, verbose_name='Signos Vitales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener entre 7 y 8 dígitos', regex='^\\d{7,8}$')], verbose_name='DNI')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['last_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción del Diagnóstico')),
                ('icd_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código ICD-10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='history.consult', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Matrícula')),
                ('specialty', models.CharField(choices=[('GP', 'Medicina General'), ('CARD', 'Cardiología'), ('DERM', 'Dermatología'), ('NEURO', 'Neurología'), ('PED', 'Pediatría'), ('GYN', 'Ginecología'), ('ORTH', 'Ortopedia'), ('PSYCH', 'Psiquiatría'), ('OTHER', 'Otra')], max_length=10, verbose_name='Especialidad')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='consult',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.doctor', verbose_name='Doctor'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('chronic_conditions', models.TextField(blank=True, null=True, verbose_name='Enfermedades Crónicas')),
                ('family_history', models.TextField(blank=True, null=True, verbose_name='Antecedentes Familiares')),
                ('social_history', models.TextField(blank=True, null=True, verbose_name='Antecedentes Sociales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='history.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
            },
        ),
        migrations.AddField(
            model_name='consult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.person', verbose_name='Paciente'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción del Tratamiento')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='Medicamentos')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instrucciones')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='history.consult', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
    ]
