# Generated by Django 4.2.16 on 2025-09-22 03:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('DOCTOR', 'Médico'), ('PATIENT', 'Paciente'), ('RECEPTION', 'Recepción'), ('NURSE', 'Enfermera')], default='PATIENT', max_length=10, verbose_name='Rol')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('report_type', models.CharField(choices=[('PATIENTS', 'Reporte de Pacientes'), ('CONSULTS', 'Reporte de Consultas'), ('DOCTORS', 'Reporte de Doctores'), ('STATISTICS', 'Estadísticas Generales'), ('CUSTOM', 'Reporte Personalizado')], max_length=20, verbose_name='Tipo de Reporte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros Aplicados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del Archivo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión')], max_length=10, verbose_name='Acción')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Objeto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
