# Generated by Django 4.2.16 on 2025-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_userprofile_report_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
